# Generated by Django 4.0.6 on 2022-07-15 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undergraduate',
            name='phone_number',
            field=models.CharField(help_text='휴대전화번호', max_length=11, validators=[django.core.validators.RegexValidator(regex='^[0-9]{3}[0-9]{4}[0-9]{4}$')]),
        ),
    ]
