# Generated by Django 4.0.6 on 2022-07-17 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField()),
                ('undergraduate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backoffice.undergraduate')),
            ],
        ),
    ]
